var annotated_dup =
[
    [ "Camera", "classspider__engine_1_1rendering_1_1_camera.html", null ],
    [ "ConstantBuffer", "classspider__engine_1_1d3dx12_1_1_constant_buffer.html", null ],
    [ "ConstantBufferData", "structspider__engine_1_1d3dx12_1_1_constant_buffer_data.html", null ],
    [ "ConstantBufferVariable", "structspider__engine_1_1d3dx12_1_1_constant_buffer_variable.html", null ],
    [ "CoreEngine", "classspider__engine_1_1core__engine_1_1_core_engine.html", null ],
    [ "DebugConsole", "classspider__engine_1_1_debug_console.html", null ],
    [ "DescriptorHeap", "structspider__engine_1_1d3dx12_1_1_descriptor_heap.html", null ],
    [ "DX12Compiler", "classspider__engine_1_1d3dx12_1_1_d_x12_compiler.html", null ],
    [ "DX12Renderer", "classspider__engine_1_1d3dx12_1_1_d_x12_renderer.html", null ],
    [ "FrameData", "structspider__engine_1_1rendering_1_1_frame_data.html", null ],
    [ "HeapAllocator", "classspider__engine_1_1d3dx12_1_1_heap_allocator.html", null ],
    [ "IndexArrayBuffer", "structspider__engine_1_1d3dx12_1_1_index_array_buffer.html", null ],
    [ "Mesh", "structspider__engine_1_1d3dx12_1_1_mesh.html", null ],
    [ "RenderingSystemDescription", "structspider__engine_1_1core__engine_1_1_rendering_system_description.html", null ],
    [ "Renderizable", "structspider__engine_1_1d3dx12_1_1_renderizable.html", null ],
    [ "RenderPipeline", "classspider__engine_1_1d3dx12_1_1_render_pipeline.html", null ],
    [ "RenderPipelineRequirements", "structspider__engine_1_1d3dx12_1_1_render_pipeline_requirements.html", null ],
    [ "ResourceBindingData", "structspider__engine_1_1d3dx12_1_1_resource_binding_data.html", null ],
    [ "Sampler", "classspider__engine_1_1d3dx12_1_1_sampler.html", null ],
    [ "SamplerData", "structspider__engine_1_1d3dx12_1_1_sampler_data.html", null ],
    [ "Shader", "structspider__engine_1_1d3dx12_1_1_shader.html", null ],
    [ "ShaderData", "structspider__engine_1_1d3dx12_1_1_shader_data.html", null ],
    [ "ShaderDescription", "classspider__engine_1_1d3dx12_1_1_shader_description.html", null ],
    [ "ShaderResourceView", "classspider__engine_1_1d3dx12_1_1_shader_resource_view.html", null ],
    [ "ShaderResourceViewData", "structspider__engine_1_1d3dx12_1_1_shader_resource_view_data.html", null ],
    [ "SynchronizationObject", "classspider__engine_1_1d3dx12_1_1_synchronization_object.html", null ],
    [ "Texture2D", "structspider__engine_1_1d3dx12_1_1_texture2_d.html", null ],
    [ "Transform", "structspider__engine_1_1rendering_1_1_transform.html", null ],
    [ "UsePathPolicy", "structspider__engine_1_1d3dx12_1_1_use_path_policy.html", null ],
    [ "UseSourcePolicy", "structspider__engine_1_1d3dx12_1_1_use_source_policy.html", null ],
    [ "Vertex", "structspider__engine_1_1d3dx12_1_1_vertex.html", null ],
    [ "VertexArrayBuffer", "structspider__engine_1_1d3dx12_1_1_vertex_array_buffer.html", null ],
    [ "Window", "classspider__engine_1_1core__engine_1_1_window.html", null ]
];